# Generated by Django 2.2.26 on 2022-06-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regionapp', '0003_auto_20220620_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_picture',
        ),
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.ImageField(null=True, upload_to='posts/'),
        ),
    ]
